### ISSUE TITLE
Create models and controllers for lessons

### ISSUE THREAD

**Issue by tuzz** [RaspberryPiFoundation/editor-api#239]

**Comment by floehopper** [comment]
@sra405 

I've been through all (126!) commits, reading each commit note and browsing each diff concentrating on the changes to the models and permissions. It all makes reasonable sense to me, but I'm not sure you should draw too many conclusions from that! 😓 I'll add some more specific notes/questions in separate comments.

I wanted to mention that merging such a big PR for the API without any of the frontend (or any end-to-end tests) being in place beforehand makes me quite nervous. However, I suspect my nervousness is mostly because it's not the way we usually work. As I think @chrislo has mentioned previously, we would typically build vertical slices through an app from the outside-in, starting with acceptance/integration tests hitting the browser and just building the bits of the API that we need for the current bit of functionality.

Anyway, I'm going to have a look in a bit more detail at the changes related to the `Project` model as you highlighted that as your main area of concern at this point.

**Comment by floehopper** [comment]
@sra405 

A couple of questions:
* Has the API for the `ProfileApiClient` been built yet? If yes, should we look at wiring that up before merging this? If not, are there any dangers of merging this with the hard-coded responses?
* Does the `HydraPublicApi` return the `organisations` keys yet? If yes, should we look at replacing `User.temporarily_add_organisations_until_the_profile_app_is_updated`? If not, are there any dangers of merging this with the hard-coded return value?

**Comment by floehopper** [comment]
@sra405 

In terms of some notable *changes* (as opposed to additions) affecting projects or other existing entities:

* When creating a project:
    * a school owner must specify who the project's owner is
    * a school teacher may only create projects they own
* `Api::ProjectsController#create` & `Api::ProjectsController#create` respond with slightly different HTTP status codes
* The `Api::ProjectsController#show` action now returns some extra data:
    * an array of its components
    * its parent if it has one
* A `User` has some extra validation so we might want to check that all the existing users will still be valid:
    * `validate :user_has_a_role_within_the_school`
    * `validate :user_is_the_owner_of_the_lesson`

I haven't yet looked at the `editor-ui` / `editor-standalone` code to see whether any of the above might cause us any issues, but I'm happy to do that if it would help.

**Comment by floehopper** [comment]
Thanks, @tuzz. That's useful context. Just to be clear, my comments are no reflection on the quality of the code which looks great! I'm just wondering how best to incorporate it into the app as a whole.

I'll take a look at rebasing the branch now.

**Comment by floehopper** [comment]
I think we've finally got to the bottom of what was going on here 😅.

It looks as @tuzz first created #233 which got merged into `main` as a single squashed merge commit, he then added more commits to the _same_ branch (without rebasing it) and used that to open #241. So although GitHub was suggesting that PR was made up of 126 commits, in fact there were only more like 37 un-merged commits. In the meantime some changes have been made to `main` including the introduction of `User#admin?` for the dashboards in #242 which conflicted somewhat with the new commits in #241.

We've opened [this new PR](https://github.com/RaspberryPiFoundation/editor-api/pull/258) with a rebased version of the unmerged changes in #241, i.e. mostly Lesson-related changes. See the PR description for more details.

@tuzz Please let us know if any of that sounds wrong! 🙏

**Comment by floehopper** [comment]
https://github.com/RaspberryPiFoundation/editor-api/pull/258 this has now been merged

**Comment by floehopper** [comment]
> Apologies for not replying in this thread!

No worries!

> I think we discussed and got to the bottom of these...

Yes, we did!

**Comment by floehopper** [comment]
* I’ve tested creating/remixing/saving/renaming/deleting projects on https://staging-editor.raspberrypi.org which I can see is pointing at https://staging-editor-api.raspberrypi.org/ and that all still seems to work OK :tada:.
* I was not initially able to access the admin dashboard at https://staging-editor-api.raspberrypi.org/admin, because my user did not have the "editor-admin" role which is as it should be. Once @sra405 had added that role to my account in staging I was then able to access the dashboard.

So we went ahead and deployed to production (thanks, @sra405) and did some similar manual testing and everything looks good! 🎉 

Moving to the "Deployed" column.
