### ISSUE TITLE
Determine if we handle app errors correctly outside local dev

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-api#244]
Currently there's a block that appears to only consider local requests before categorising the requests correctly. I believe this results in 500s being returned by the app in staging/prod. Needs investigating.

♻️ I think you're right about this block, I'm pretty sure we only get 500s from the app in production if these cases occur. I'll backlog it 👍

_Originally posted by @sra405 in https://github.com/RaspberryPiFoundation/editor-api/pull/233#discussion_r1500716950_

**Comment by chrisroos** [comment]
> Currently there's a block that appears to only consider local requests before categorising the requests correctly. I believe this results in 500s being returned by the app in staging/prod. Needs investigating.

It's actually the other way around. [The block](https://github.com/RaspberryPiFoundation/editor-api/blob/fce9e4e33d3ca697501d2e75f3cc8d627c7db4bf/app/controllers/api_controller.rb#L8-L13) only categorises the errors correctly when `consider_all_requests_local` is false (i.e. test and production envs). I've opened a PR to remove the condition in https://github.com/RaspberryPiFoundation/editor-api/pull/275 so that we see consistent behaviour in all environments.
