### ISSUE TITLE
GET /api/schools/<ID>: marking a school as verified causes a HTTP 403

### ISSUE THREAD

**Issue by conorriches** [RaspberryPiFoundation/editor-api#284]
### The bug
Being able to view a school in `editor-standalone` is not possible unless the school is unverfied

### To replicate
* If a school is created using the form (`/en/schools/new`), it's possible to view the school on `editor-standalone`at `/en/schools/<ID>`. 
* If you mark this school as verified, the editor-api responds with HTTP 403.

**Comment by loiswells97** [comment]
## Findings

- The problem seems to be that the user's `organisation_ids` are just being given a placeholder value until the roles stuff is set up properly.
-  However, the school is now being given a proper UUID, which means that the school id no longer matches the fake organisaiton id being given to the user
- Therefore, since users are only able to load schools for with ids matching the organisations to which they belong, the user gets Access Denied when they try to load a school.

**Comment by sra405** [comment]
Gotcha, thanks for this! Great deduction skills. It comes across as a bit of a non-problem then in all honesty. We're working on keeping the `organisation_ids` stuff in `editor-api` and there won't be `organisations` returned from profile at all. Might be good to catchup with @chrislo and @chrisroos as they've worked on keeping `schools` in our API and currently working on role 👍
