### ISSUE TITLE
Remove class member endpoint

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-api#417]
- [x] add endpoint to remove class members from the table
- [x] audit the class members table due to this being the first instance of an edit

**Comment by conorriches** [comment]
### Rough notes
When you delete student, in profile, the deleted_at flag is set
This causes a 422 from editor-api, as there is now a 404 from profile
The 404 happens because the student can't be found, but ID is requested by API
Student ID comes from class_members table
If we delete row from `class_memebers` table, it works. But do we want to delete or soft delete?
