### ISSUE TITLE
Spike: Limit saved editor file sizes

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-api#462]
Twice now `editor-api` has experienced ~30min downtime due to a single user copy/pasting strings in the editor. These users have been logged in meaning the files are auto-saved, when the request reaches a certain size the API experiences a memory spike and crashes.

This spike is to investigate the cause (is it line legth? File size? GET/POST limits?) and propose a fix.

Useful slack threads:
- https://raspberrypifoundation.slack.com/archives/C02JBAA2NFP/p1731402678428489
- https://raspberrypifoundation.slack.com/archives/C02JBAA2NFP/p1728655670996699

**Comment by loiswells97** [comment]
## Findings

- Files/components with 10 million characters and above result in a memory spike and a `Memory quota exceeded` message in the logs
- These memory spikes continue, with further `Memory quota exceeded messages` appearing in logs for other requests that are much smaller
- Files with 8.5 million characters do not cause a memory spike, but if large requests of this size are sent soon after each other, the message appears in the logs
- Multiple large files with a combined total number of characters well above the 10 million limit do not cause a memory spike, and the breakdown of time spent processing the request reveals that the majority of the latency caused by large requests is due to `ActiveRecord`, suggesting that the stage where the components are being saved in the database is the bottleneck that is causing the issues. That helps explain why the issues are not triggered by combined file size, but do appear when the size of an individual file exceeds a certain limit.

**Comment by loiswells97** [comment]
## Possible approaches

- Add a limit to the Codemirror instance that prevents users from entering more than a certain number of characters. We might need some design to help explain to users who try to paste massive files in why that isn't working, e.g. a modal that pops up telling them about the file size limit
- Add a limit to the `content` attribute of the `Component` class in the backend that ensures that components with more than a certain number of characters are not considered valid, and therefore won't be saved in the database
- Add a limit to the content column of the component table in the database to prevent excessively large files being saved - we are not enforcing any other validations on the database at the moment, just having them on the model - do we want to stick with this pattern in case we ever change the limit, as otherwise we would risk the database and model validations getting out of sync?
- Limit the number of characters allowed in a project overall (this may not be necessary since we are able to save files with a combined character count of over 10 million without a problem)
- Add a job to save projects into the database to prevent large requests coming one after the other causing memory limit problems
- Only save files that have been changed, not all files, when a change is made.
